<div class="modal fade" id="modalRegistroManiobra" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" style="z-index: 1100;">
    <div class="modal-dialog modal-dialog-scrollable modal-xl">
        <div class="modal-content">
            <div class="modal-body">
                <form name="frmEditarManiobra" id="frmEditarManiobra" onsubmit="return false" autocomplete="off">
                    <div class="d-flex flex-row justify-content-between align-items-start">
                        <img src="../../img/logos/logoGruas.png" alt="Imagen Redonda" width="90" height="90">
                        <!-- class="rounded-circle -->
                        <div class="d-flex flex-column w-100 ps-4">
                            <div class="d-flex">
                                <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                    <label for="txtModalRegistroInventario" class="form-label me-2">Inventario</label>
                                    <input class=" form-control border-bottom px-2 pb-0" id="txtModalRegistroInventario"
                                        name="txtModalRegistroInventario" type="text">
                                </div>
                                <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                    <label for="txtModalRegistroFechaInicio" class="form-label me-2">Fecha</label>
                                    <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroFechaInicio"
                                        name="txtModalRegistroFechaInicio" type="datetime-local">
                                </div>
                            </div>
                            <div class="d-flex flex-column border rounded-pill p-2 text-center">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Servicios auxiliares de arrastre,
                                    salvamento, guarda, custodia y depósito de vehículos</h1>
                            </div>
                        </div>
                    </div>

                    <h1 class="modal-title fs-5 ms-2 mt-4" id="staticBackdropLabel">Datos del vehículo</h1>
                    <div class="d-flex flex-column w-100">
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroMarca" class="form-label me-2">Marca</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroMarca"
                                    name="txtModalRegistroMarca" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroTipo" class="form-label me-2">Tipo</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroTipo"
                                    name="txtModalRegistroTipo" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroNoSerie" class="form-label me-2">No.Serie</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroNoSerie"
                                    name="txtModalRegistroNoSerie" type="text">
                            </div>
                        </div>

                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroModelo" class="form-label me-2">Modelo</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroModelo"
                                    name="txtModalRegistroModelo" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroColor" class="form-label me-2">Color</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroColor"
                                    name="txtModalRegistroColor" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroMotor" class="form-label me-2">Motor</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroMotor"
                                    name="txtModalRegistroMotor" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroPlaca" class="form-label me-2">Placa</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroPlaca"
                                    name="txtModalRegistroPlaca" type="text">
                            </div>
                        </div>

                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroRemolque" class="form-label me-2">Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroRemolque"
                                    name="txtModalRegistroRemolque" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroSerieRemolque" class="form-label text-nowrap me-2">No.Serie
                                    Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroSerieRemolque"
                                    name="txtModalRegistroSerieRemolque" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroPlacaRemolque" class="form-label text-nowrap me-2">Placa
                                    Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroPlacaRemolque"
                                    name="txtModalRegistroPlacaRemolque" type="text">
                            </div>
                        </div>

                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroSegundoRemolque" class="form-label text-nowrap me-2">2°
                                    Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroSegundoRemolque"
                                    name="txtModalRegistroSegundoRemolque" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroSegundoSerieRemolque" class="form-label text-nowrap me-2">2° No.Serie
                                    Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroSegundoSerieRemolque"
                                    name="txtModalRegistroSegundoSerieRemolque" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroSegundoPlacaRemolque" class="form-label text-nowrap me-2">2° Placa
                                    Remolque</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroSegundoPlacaRemolque"
                                    name="txtModalRegistroSegundoPlacaRemolque" type="text">
                            </div>
                        </div>

                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroDolly" class="form-label me-2">Dolly</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroDolly"
                                    name="txtModalRegistroDolly" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroSerieDolly" class="form-label text-nowrap me-2">No.Serie Dolly</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroSerieDolly"
                                    name="txtModalRegistroSerieDolly" type="text">
                            </div>
                        </div>
                    </div>

                    <h1 class="modal-title fs-5 ms-2 mt-4" id="staticBackdropLabel">Motivo de la retención del vehículo</h1>
                    <div class="d-flex flex-column w-100">
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroAutoridad" class="form-label me-2">Autoridad</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroAutoridad"
                                    name="txtModalRegistroAutoridad" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroMotivo" class="form-label text-nowrap me-2">Motivo</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroMotivo"
                                    name="txtModalRegistroMotivo" type="text">
                            </div>
                        </div>
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-100 p-2">
                                <label for="txtModalRegistroDisposicion" class="form-label me-2">A disposición de:</label>
                                <textarea class="form-control border px-2 pb-0" id="txtModalRegistroDisposicion"
                                    name="txtModalRegistroisposicion" rows="4"></textarea>
                            </div>
                        </div>
                    </div>

                    <h1 class="modal-title fs-5 ms-2 mt-4" id="staticBackdropLabel">Servicio</h1>
                    <div class="d-flex flex-column w-100">
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-40 p-2">
                                <label for="txtModalRegistroFechaSalida" class="form-label text-nowrap me-2">Fecha de
                                    salida</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroFechaSalida"
                                    name="txtModalRegistroFechaSalida" type="datetime-local">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroNumFactura" class="form-label text-nowrap me-2">Número Factura</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroNumFactura"
                                    name="txtModalRegistroNumFactura" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-30 p-2">
                                <label for="txtModalRegistroCostoFinal" class="form-label text-nowrap me-2">Costo final</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroCostoFinal"
                                    name="txtModalRegistroCostoFinal" type="text">
                            </div>
                        </div>
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroIva" class="form-label me-2">IVA</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroIva"
                                    name="txtModalRegistroIva" type="text">
                            </div>
                            <div class="d-flex flex-row align-items-baseline w-50 p-2">
                                <label for="txtModalRegistroTotal" class="form-label text-nowrap me-2">Total</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroTotal"
                                    name="txtModalRegistroTotal" type="text">
                            </div>
                        </div>
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-100 p-2">
                                <label for="txtModalRegistroObservacionesFinales" class="form-label me-2">Observaciones
                                    finales</label>
                                <textarea class="form-control border px-2 pb-0" id="txtModalRegistroObservacionesFinales"
                                    name="txtModalRegistroObservacionesFinales" rows="4"></textarea>
                            </div>
                        </div>
                        <div class="d-flex w-100">
                            <div class="d-flex flex-row align-items-baseline w-25 p-2">
                                <label for="txtModalRegistroEstatus" class="form-label me-2">Estatus</label>
                                <input class="form-control border-bottom px-2 pb-0" id="txtModalRegistroEstatus"
                                    name="txtModalRegistroEstatus" type="text">
                            </div>
                        </div>
                    </div>

                    <!-- <div class="d-flex w-100">
                            <label for="txtEstatus" class="form-label">Estatus</label>
                            <select id="txtEstatus" name="txtEstatus" class="form-select border-bottom px-2 pb-0">
                                <option selected>Open this select menu</option>
                                <option value="0">No Disponible</option>
                                <option value="1">Disponible</option>
                            </select>
                        </div> -->
                </form>
            </div>
            <div class="modal-footer">
                <button id="btnCerrarRegistroManiobra" type="button" class="btn btnCerrarManiobra btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>