<div class="card">
    <div class="card-header pb-0">
        <div class="row">
            <div class="col-lg-6 col-7">
                <h6>Tabla</h6>
                <p class="text-sm mb-0">
                    <i class="fa fa-check text-info" aria-hidden="true"></i>
                    <span class="font-weight-bold ms-1">Información</span> de operadores
                </p>
            </div>
            <!-- BTNS -->
            <div class="col-lg-6 col-5 my-auto text-end">
                <a class="btn btn-outline-success btn-sm mb-0 me-3 btnExcelOperadores">
                    Exportar Excel
                </a>
                <!-- <div class="dropdown float-lg-end pe-4">
                                        <a class="cursor-pointer" id="dropdownTable" data-bs-toggle="dropdown"
                                            aria-expanded="false">
                                            <i class="fa fa-ellipsis-v text-secondary"></i>
                                        </a>
                                        <ul class="dropdown-menu px-2 py-3 ms-sm-n4 ms-n5"
                                            aria-labelledby="dropdownTable">
                                            <li><a class="dropdown-item border-radius-md" href="javascript:;">Action</a>
                                            </li>
                                            <li><a class="dropdown-item border-radius-md" href="javascript:;">Another
                                                    action</a></li>
                                            <li><a class="dropdown-item border-radius-md" href="javascript:;">Something
                                                    else here</a></li>
                                        </ul>
                                    </div> -->
            </div>
        </div>
    </div>
    <div class="card-body px-0 pb-2">
        <div class="table-responsive">
            <!-- EMPIEZA DATATABLE -->
            <table id="dataTblOperadores" class="table align-items-center mb-0">
                <thead>
                    <tr>
                        <th class="text-secondary text-center text-sm font-weight-bolder opacity-7">
                            #</th>
                        <th class="text-secondary text-center text-sm font-weight-bolder opacity-7">
                            Operador</th>
                        <th class="text-secondary text-center text-sm font-weight-bolder opacity-7">
                            Estatus</th>
                    </tr>
                </thead>
                <tbody id="tblOperadores" class="table align-items-center mb-0">
                    <tr>
                        <td class="align-middle text-center text-sm">
                            <span class="text-xs font-weight-bold"> 1 </span>
                        </td>
                        <td class="align-middle text-center text-sm">
                            <span class="text-xs font-weight-bold"> $14,000 </span>
                        </td>
                        <td class="align-middle text-center text-sm">
                            <span class="text-xs font-weight-bold"> $14,000 </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>