<tr class="">
    <td class="align-left text-center text-sm py-3">
        <span class="text-md font-weight-bold">[count]</span>
    </td>
    <td class="align-middle text-center text-md">
        <span class="text-md font-weight-bold">[nombreOperador]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[nombreEncargado]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[economico]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[nombreMunicipio]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[ubicacion]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[inventario]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[fechaInicio]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[fechaFin]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[costo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <a class="btnVerImgVehiculos" data-bs-toggle="modal" data-bs-target="#modalImgVehiculos" data-idmaniobra="[idManiobra]" style="cursor: pointer;">
            <i class="fas fa-images text-lg"></i>
        </a>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[observaciones]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[fechaRegistro]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[marcaVehiculo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[modeloVehiculo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[anoVehiculo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[placaVehiculo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[serieVehiculo]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[color]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[motor]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[remolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[serieRemolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[placaRemolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[segundoRemolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[serieSegundoRemolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[placaSegundoRemolque]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[dolly]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[serieDolly]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[autoridad]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[motivoRetencion]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[disposicion]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[fechaSalida]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[numFactura]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[costoFinal]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[iva]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[total]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[observacionesFinales]</span>
    </td>
    <td class="align-middle text-center text-sm">
        <span class="text-md font-weight-bold">[estatus]</span>
    </td>
    <td class="align-middle text-center text-xs">
        <a class="btnIngresoDeposito" data-bs-toggle="modal" data-bs-target="#modalIngresoDeposito" data-idmaniobra="[idManiobra]" style="cursor: pointer;">
            <i class="fas fa-sign-in-alt text-lg"></i>
        </a>
    </td>
    <td class="align-middle text-center text-xs">
        <a class="btnSalidaDeposito" data-bs-toggle="modal" data-bs-target="#modalSalidaDeposito" data-idmaniobra="[idManiobra]" style="cursor: pointer;">
        <i class="fas fa-sign-out-alt text-lg"></i>
        </a>
    </td>
    <td class="align-middle text-center text-xs">
        <a class="btnEditarManiobra" data-bs-toggle="modal" data-bs-target="#modalEditarManiobra" data-idmaniobra="[idManiobra]" style="cursor: pointer;">
            <i class="fas fa-pen text-lg"></i>
        </a>
    </td>
    <td class="align-middle text-center text-xs">
        <a class="btnRegistroManiobra" data-bs-toggle="modal" data-bs-target="#modalRegistroManiobra" data-idmaniobra="[idManiobra]" style="cursor: pointer;">
            <i class="fas fa-eye text-lg"></i>
        </a>
    </td>
</tr>