<li class="nav-item dropend seccion[idSeccion]">
    <a class="nav-link [classSeccion] dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">table_view</i>
        </div>
        <span class="nav-link-text ms-1">[seccion]&nbsp;</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark">
        [subSecciones]
        <!-- <li><a class="dropdown-item">[subSeccion]</a></li>
        <li><a class="dropdown-item">[subSeccion]</a></li> -->
    </ul>
</li>