<li class="nav-item mt-10">
    <a id="btnLogOut" class="nav-link text-white bg-gradient-danger" style="cursor: pointer;">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center"
            style="pointer-events: none;">
            <i class="material-icons opacity-10">login</i>
        </div>
        <span class="nav-link-text font-weight-normal ms-1" style="pointer-events: none;">Salir</span>
    </a>
</li>